"""add developer platform and article locations

Revision ID: 32be9c30a1cc
Revises: a7e7f83866b4
Create Date: 2026-07-31 22:39:49.792325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be9c30a1cc'
down_revision: Union[str, None] = 'a7e7f83866b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('what_are_you_building', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='developer_tier', create_type=False, create_constraint=True), server_default='FREE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developers'))
    )
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.create_index(op.f('ix_developers_email_verification_token'), 'developers', ['email_verification_token'], unique=False)
    op.create_table('developer_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_developer_apps_developer_id_developers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developer_apps'))
    )
    op.create_index(op.f('ix_developer_apps_developer_id'), 'developer_apps', ['developer_id'], unique=False)
    op.create_table('developer_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.Enum('LIVE', 'TEST', name='developer_key_environment', create_constraint=True), server_default='LIVE', nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='developer_tier', create_constraint=True), server_default='FREE', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['developer_apps.id'], name=op.f('fk_developer_api_keys_app_id_developer_apps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_developer_api_keys_developer_id_developers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developer_api_keys'))
    )
    op.create_index(op.f('ix_developer_api_keys_app_id'), 'developer_api_keys', ['app_id'], unique=False)
    op.create_index(op.f('ix_developer_api_keys_developer_id'), 'developer_api_keys', ['developer_id'], unique=False)
    op.create_index(op.f('ix_developer_api_keys_key_hash'), 'developer_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_developer_api_keys_key_prefix'), 'developer_api_keys', ['key_prefix'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['developer_api_keys.id'], name=op.f('fk_usage_counters_api_key_id_developer_api_keys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_usage_counters_developer_id_developers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_counters')),
    sa.UniqueConstraint('api_key_id', 'date', name='uq_usage_counters_api_key_id_date')
    )
    op.create_index(op.f('ix_usage_counters_api_key_id'), 'usage_counters', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_counters_developer_id'), 'usage_counters', ['developer_id'], unique=False)
    op.create_index('ix_usage_counters_developer_id_date', 'usage_counters', ['developer_id', 'date'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['developer_api_keys.id'], name=op.f('fk_usage_logs_api_key_id_developer_api_keys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_usage_logs_developer_id_developers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_logs'))
    )
    op.create_index('ix_usage_logs_api_key_created_at', 'usage_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_api_key_id'), 'usage_logs', ['api_key_id'], unique=False)
    op.create_index('ix_usage_logs_developer_created_at', 'usage_logs', ['developer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_developer_id'), 'usage_logs', ['developer_id'], unique=False)
    op.add_column('articles', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('location_state', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('location_country', sa.String(length=100), nullable=True))
    op.alter_column('articles', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_index(op.f('ix_articles_reporter_id'), 'articles', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.add_column('bookmarks', sa.Column('reel_id', sa.UUID(), nullable=True))
    op.alter_column('bookmarks', 'article_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_bookmarks_user_reel', 'bookmarks', ['user_id', 'reel_id'])
    op.create_foreign_key(op.f('fk_bookmarks_reel_id_reels'), 'bookmarks', 'reels', ['reel_id'], ['id'], ondelete='CASCADE')
    op.add_column('comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_comments_parent_id_comments'), 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('is_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('reading_history', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'reading_history')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'state')
    op.drop_column('users', 'country')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('notifications', 'is_sent')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_constraint(op.f('fk_comments_parent_id_comments'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    op.drop_constraint(op.f('fk_bookmarks_reel_id_reels'), 'bookmarks', type_='foreignkey')
    op.drop_constraint('uq_bookmarks_user_reel', 'bookmarks', type_='unique')
    op.alter_column('bookmarks', 'article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bookmarks', 'reel_id')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_reporter_id'), table_name='articles')
    op.alter_column('articles', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('articles', 'location_country')
    op.drop_column('articles', 'location_state')
    op.drop_column('articles', 'location')
    op.drop_index(op.f('ix_usage_logs_developer_id'), table_name='usage_logs')
    op.drop_index('ix_usage_logs_developer_created_at', table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_api_key_id'), table_name='usage_logs')
    op.drop_index('ix_usage_logs_api_key_created_at', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index('ix_usage_counters_developer_id_date', table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_developer_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_api_key_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_developer_api_keys_key_prefix'), table_name='developer_api_keys')
    op.drop_index(op.f('ix_developer_api_keys_key_hash'), table_name='developer_api_keys')
    op.drop_index(op.f('ix_developer_api_keys_developer_id'), table_name='developer_api_keys')
    op.drop_index(op.f('ix_developer_api_keys_app_id'), table_name='developer_api_keys')
    op.drop_table('developer_api_keys')
    op.drop_index(op.f('ix_developer_apps_developer_id'), table_name='developer_apps')
    op.drop_table('developer_apps')
    op.drop_index(op.f('ix_developers_email_verification_token'), table_name='developers')
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
