"""add_reel_comment_parent_like

Revision ID: 8a882471f4e3
Revises: c640f9a85366
Create Date: 2026-07-15 20:00:50.949036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a882471f4e3'
down_revision: Union[str, None] = 'c640f9a85366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_comment_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['reel_comments.id'], name=op.f('fk_reel_comment_likes_comment_id_reel_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reel_comment_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reel_comment_likes'))
    )
    op.add_column('reel_comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('reel_comments', sa.Column('like_count', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_reel_comments_parent_id_reel_comments'), 'reel_comments', 'reel_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reel_comments_parent_id_reel_comments'), 'reel_comments', type_='foreignkey')
    op.drop_column('reel_comments', 'like_count')
    op.drop_column('reel_comments', 'parent_id')
    op.drop_table('reel_comment_likes')
    # ### end Alembic commands ###
