"""add_article_analytics_and_revision_snapshots

Revision ID: b74ee9845f2f
Revises: 32be9c30a1cc
Create Date: 2026-08-01 11:53:53.554399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74ee9845f2f'
down_revision: Union[str, None] = '32be9c30a1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('read_depth_percent', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('device_platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_analytics_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_article_analytics_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_analytics'))
    )
    op.create_index(op.f('ix_article_analytics_article_id'), 'article_analytics', ['article_id'], unique=False)
    op.create_index('ix_article_analytics_article_id_created_at', 'article_analytics', ['article_id', 'created_at'], unique=False)
    op.add_column('article_revisions', sa.Column('content_snapshot', sa.Text(), nullable=True))
    op.add_column('article_revisions', sa.Column('title_snapshot', sa.String(length=500), nullable=True))
    op.add_column('article_revisions', sa.Column('change_summary', sa.String(length=500), nullable=True))
    op.add_column('article_revisions', sa.Column('revision_type', sa.String(length=50), server_default=sa.text("'unknown'"), nullable=False))
    op.add_column('articles', sa.Column('slug', sa.String(length=300), nullable=True))
    op.add_column('articles', sa.Column('seo_title', sa.String(length=70), nullable=True))
    op.add_column('articles', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('articles', sa.Column('canonical_url', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('image_alt_text', sa.String(length=300), nullable=True))
    op.add_column('articles', sa.Column('correction_notice', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('correction_added_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('correction_added_by_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('is_breaking_update', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('articles', sa.Column('post_publish_edit_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('articles', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('articles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('delete_reason', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_articles_is_deleted'), 'articles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_foreign_key(op.f('fk_articles_deleted_by_id_users'), 'articles', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_articles_correction_added_by_id_users'), 'articles', 'users', ['correction_added_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_articles_correction_added_by_id_users'), 'articles', type_='foreignkey')
    op.drop_constraint(op.f('fk_articles_deleted_by_id_users'), 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_deleted'), table_name='articles')
    op.drop_column('articles', 'delete_reason')
    op.drop_column('articles', 'deleted_by_id')
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'is_deleted')
    op.drop_column('articles', 'scheduled_at')
    op.drop_column('articles', 'post_publish_edit_count')
    op.drop_column('articles', 'is_breaking_update')
    op.drop_column('articles', 'correction_added_by_id')
    op.drop_column('articles', 'correction_added_at')
    op.drop_column('articles', 'correction_notice')
    op.drop_column('articles', 'image_alt_text')
    op.drop_column('articles', 'canonical_url')
    op.drop_column('articles', 'meta_description')
    op.drop_column('articles', 'seo_title')
    op.drop_column('articles', 'slug')
    op.drop_column('article_revisions', 'revision_type')
    op.drop_column('article_revisions', 'change_summary')
    op.drop_column('article_revisions', 'title_snapshot')
    op.drop_column('article_revisions', 'content_snapshot')
    op.drop_index('ix_article_analytics_article_id_created_at', table_name='article_analytics')
    op.drop_index(op.f('ix_article_analytics_article_id'), table_name='article_analytics')
    op.drop_table('article_analytics')
    # ### end Alembic commands ###
