"""add_aspect_ratio_to_reels

Revision ID: c640f9a85366
Revises: 1cb3fdd32080
Create Date: 2026-07-15 07:21:59.995460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c640f9a85366'
down_revision: Union[str, None] = '1cb3fdd32080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reels', sa.Column('aspect_ratio', sa.String(length=10), server_default='16:9', nullable=False, comment='Video aspect ratio: 16:9 for landscape, 9:16 for vertical/Shorts'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reels', 'aspect_ratio')
    # ### end Alembic commands ###
